language: generic
sudo: requried
services:
  - docker

before_install:
  - docker build -t breyr/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true breyr/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react-env"
  env: "Dockerreactenv-env"
  bucket_name: "elasticbeanstalk-us-east-1-282604873655"
  bucket_path: "docker-react-env"
  on:
    branch: master
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_SECRET_KEY"
